### ISSUE TITLE
it crashed if the realm object contains byte[]

### ISSUE THREAD

**Issue by PPSong** [jonasrottmann/realm-browser#14]
First of all, thanks for your effort for such an wonderful tool
just like the title described: it crashed if the realm object contains byte[], when you click the record

**Comment by jonasrottmann** [comment]
Hi, I think this bug is solved on the develop branch. I now limit the displayed bytes to 8/1000 on the `BrowserActivity`/`ObjectActivity` which by far isn't the perfect solution, but should work until I find time to implement a better solution.
You can test this version by using: `compile "com.github.jonasrottmann.realm-browser:realm-browser:develop-SNAPSHOT"`
