### ISSUE TITLE
Confusing toast error on encrypted realm files

### ISSUE THREAD

**Issue by EdwardvanRaak** [jonasrottmann/realm-browser#15]
Small thing I noticed. Adding encryption to the Realm file and not adding the correct configuration causes this toast to show up:

> Can't open realm instance. You must close all open realm instances before opening this file.

Probably best to catch the specific realm exception for this situation to prevent any confusion.

**Comment by jonasrottmann** [comment]
Thanks for reporting 🙂 I added a catch for RealmFileException which handles the encryption error among others. This will be included in version 0.0.12. But in strongly recommend using a RealmBrowser method where you pass a RealmConfiguration instead of a file name, e.g.:
`RealmBrowser.startRealmModelsActivity(Context context, RealmConfiguration realmConfiguration)`
